### ISSUE TITLE
java -version failed in nightly runs

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#277]
The recent PR https://github.com/adoptium/TKG/pull/266 added `java -version output`. The code failed in nightly runs: 

```
00:07:04  java.io.IOException: Cannot run program "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/bin/java -version": error=2, No such file or directory
00:07:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
00:07:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
00:07:04  	at org.openj9.envInfo.CmdExecutor.execute(CmdExecutor.java:40)
00:07:04  	at org.openj9.envInfo.JavaInfo.getJavaVersion(JavaInfo.java:171)
00:07:04  	at org.openj9.envInfo.EnvDetector.getJavaInfo(EnvDetector.java:53)
00:07:04  	at org.openj9.envInfo.EnvDetector.parseArgs(EnvDetector.java:32)
00:07:04  	at org.openj9.envInfo.EnvDetector.main(EnvDetector.java:27)
00:07:04  Caused by: java.io.IOException: error=2, No such file or directory
00:07:04  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
00:07:04  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
00:07:04  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
00:07:04  	... 6 more
00:07:04  Cannot determine System.getProperty('java.version')=Command could not be executed
```
https://openj9-jenkins.osuosl.org/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/208/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_OMR/162/console
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.system_x86-64_windows_Nightly/156/console

Same error in hotspot:
```
00:01:04.380  java.io.IOException: Cannot run program "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/java -version": error=2, No such file or directory
00:01:04.380  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
00:01:04.380  	at org.openj9.envInfo.CmdExecutor.execute(CmdExecutor.java:40)
00:01:04.380  	at org.openj9.envInfo.JavaInfo.getJavaVersion(JavaInfo.java:171)
00:01:04.380  	at org.openj9.envInfo.EnvDetector.getJavaInfo(EnvDetector.java:53)
00:01:04.380  	at org.openj9.envInfo.EnvDetector.parseArgs(EnvDetector.java:32)
00:01:04.380  	at org.openj9.envInfo.EnvDetector.main(EnvDetector.java:27)
00:01:04.380  Caused by: java.io.IOException: error=2, No such file or directory
00:01:04.380  	at java.lang.UNIXProcess.forkAndExec(Native Method)
00:01:04.380  	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
00:01:04.380  	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
00:01:04.380  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
00:01:04.380  	... 5 more
00:01:04.380  Cannot determine System.getProperty('java.version')=Command could not be executed
```
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3587/console

**Comment by llxia** [comment]
@JeromeJu could you take a look? Thanks
